[env]
TERM = "xterm-256color"

[window]
decorations = "full"
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true
opacity = 0.9

[window.padding]
x = 9
y = 9

[scrolling]
history = 10000
multiplier = 3

[font]
size = 11
builtin_box_drawing = true

[font.normal]
family = "BlexMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "BlexMono Nerd Font Mono"
style = "Regular"

[font.italic]
family = "BlexMono Nerd Font Mono"
style = "Regular"

[font.bold_italic]
family = "BlexMono Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[colors.cursor]
text = "#000000"
cursor = "#9a9a9a"

[colors.primary]
background = "#1e1e1e"
foreground = "#e8e8e8"

[colors.normal]
black = "#2e2e2e"
red = "#d75f5f" 
green = "#5faf5f"
yellow = "#d7af5f"
blue = "#5fafd7"
magenta = "#af5faf"
cyan = "#5fd7af"
white = "#d0d0d0"

[colors.bright]
black = "#5e5e5e"
red = "#ff8787"
green = "#87ff87"
yellow = "#ffff87"
blue = "#87ceeb"
magenta = "#ff87ff"
cyan = "#87ffff"
white = "#ffffff"

[colors.selection]
text = "#1e1e1e"
background = "#5f87af"


[bell]
animation = "Linear"
duration = 0
color = "#171717"
command = "None"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>	"
save_to_clipboard = true




[cursor]
blink_interval = 750
unfocused_hollow = true
thickness = 0.15

[cursor.style]
shape = "Beam"
blinking = "Off"

[terminal]
osc52 = "CopyPaste"

[mouse]
hide_when_typing = false
bindings = [
    { mouse = "Middle", action = "PasteSelection" },
]

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001f\u007f-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[keyboard]
bindings = [
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "Insert", mods = "Shift", action = "PasteSelection" },
    { key = "Up", mods = "Control|Shift", action = "ScrollLineUp" },
    { key = "Down", mods = "Control|Shift", action = "ScrollLineDown" },
    { key = "PageUp", mods = "Control|Shift", action = "ScrollPageUp" },
    { key = "PageDown", mods = "Control|Shift", action = "ScrollPageDown" },
    { key = "Home", mods = "Control|Shift", action = "ScrollToTop" },
    { key = "End", mods = "Control|Shift", action = "ScrollToBottom" },
    { key = "Minus", mods = "Control|Shift", action = "DecreaseFontSize" },
    { key = "Plus", mods = "Control|Shift", action = "IncreaseFontSize" },
    { key = "Key0", mods = "Control|Shift", action = "ResetFontSize" },
    { key = "Q", mods = "Control|Shift", action = "Quit" },
    { key = "L", mods = "Control", chars = "\f" },
]

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
print_events = false
