conky.config = {
    alignment = 'top_right',
    background = false,
    double_buffer = true,
    draw_borders = false,
    draw_graph_borders = false,
    draw_outline = false,
    draw_shades = false,
    gap_x = 20,        -- distance from right edge
    gap_y = 50,        -- distance from top (clear your polybar)
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'desktop',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    update_interval = 60.0,
    use_xft = true,
    font = 'BlexMono Nerd Font:bold:size=12',
    color0 = '#b7c2d7',
};

conky.text = [[
${color0}${execpi 3600 cal}$color
]];
