conky.config = {
    alignment = 'middle_middle',
    background = false,
    cpu_avg_samples = 2,
    default_color = 'white',
    default_outline_color = 'white',
    default_shade_color = 'white',
    double_buffer = true,
    draw_borders = false,
    draw_graph_borders = true,
    draw_outline = false,
    draw_shades = false,
    gap_x = 0,
    gap_y = 0,
    maximum_width = 1600,
    no_buffers = true,
    out_to_console = false,
    out_to_stderr = false,
    extra_newline = false,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'desktop',
    own_window_transparent = true,
    own_window_argb_visual = true,
    update_interval = 1.0,
    uppercase = true,
    use_spacer = 'none',
    use_xft = true,
    font = 'BlexMono Nerd Font:bold:size=100',
};

conky.text = [[
${color white}${time %H:%M:%S}
]];
